package quitanda.models;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Compra composed by four fields (id, produto, tipo produto, unidade de medida, quantidade, preco). The
 * Entity annotation indicates that this class is a JPA entity. The Table
 * annotation specifies the name for the table in the db.
 *
 * @author Eric Sakamoto
 */
@Entity
@Table(name = "compras")
public class Compra {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// Data da compra
	@NotNull
	private Date data;
	
	// Nome do Produto
	@NotNull
	private String produto;

	// Tipo do Produto
	@NotNull
	private String tipo;

	// Unidade do Produto
	@NotNull
	private String unidade;
	
	// Quantidade
	@NotNull
	private Integer quantidade;
	
	// Preco
	@NotNull
	private Float preco;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public Compra() {
	}

	public Compra(long id) {
		this.id = id;
	}

	public Compra(String produto, String tipo, String unidade, Integer quantidade, Float preco, Date data) {
		this.produto = produto;
		this.tipo = tipo;
		this.unidade = unidade;
		this.quantidade = quantidade;
		this.preco = preco;
		this.data = data;
	}

	// Getter and setter methods
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getProduto() {
		return produto;
	}

	public void setProduto(String produto) {
		this.produto = produto;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getUnidade() {
		return unidade;
	}

	public void setUnidade(String unidade) {
		this.unidade = unidade;
	}

	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	public Float getPreco() {
		return preco;
	}

	public void setPreco(Float preco) {
		this.preco = preco;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

} // class Compra
