package quitanda.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Produto composed by four fields (id, nome, tipo, unidade). The
 * Entity annotation indicates that this class is a JPA entity. The Table
 * annotation specifies the name for the table in the db.
 *
 * @author Eric Sakamoto
 */
@Entity
@Table(name = "produtos")
public class Produto {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// Nome do Produto
	@NotNull
	private String nome;

	// Tipo do Produto
	@NotNull
	private String tipo;
	
	// Unidade Padrão do Produto
	@NotNull
	private String unidade;	

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public Produto() {
	}

	public Produto(long id) {
		this.id = id;
	}

	public Produto(String nome, String tipo) {
		this.nome = nome;
		this.tipo = tipo;
	}

	// Getter and setter methods
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getUnidade() {
		return unidade;
	}

	public void setUnidade(String unidade) {
		this.unidade = unidade;
	}
	
	
} // class Produto
