package quitanda.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Tipo composed by 2 fields (id, nome). The
 * Entity annotation indicates that this class is a JPA entity. The Table
 * annotation specifies the name for the table in the db.
 *
 * @author Eric Sakamoto
 */
@Entity
@Table(name = "tipos")
public class Tipo {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// Nome do Tipo
	@NotNull
	private String nome;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public Tipo() {
	}

	public Tipo(long id) {
		this.id = id;
	}

	public Tipo(String nome) {
		this.nome = nome;
	}

	// Getter and setter methods
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

} // class Tipo
